[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.33.0", features = ["bundled"] }
actix-web = "4"
serde_json = "1.0"
serde = {version = "1.0", features = ["derive"]}
